### ISSUE TITLE
Don't suggest attributes for internal/private methods

### ISSUE THREAD

**Issue by gep13** [WormieCorp/Cake.Addin.Analyzer#22]
As discussed on this [issue](https://github.com/cake-build/cake/pull/3183#issuecomment-782904066) the analyzer shouldn't suggest adding an attribute on internal/private methods.

**To Reproduce**
1. Build the Cake.Gitter project (without the attributes that were added in this [commit](https://github.com/cake-contrib/Cake.Gitter/commit/3ef7e572b750ced153fd41397c4cff343737a39e))
2. See the attribute being suggested

**Expected behavior**
The attribute shouldn't be recommended to be added.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.1.1

**Additional context**
N/A

**Comment by AdmiringWorm** [comment]
Thank you for opening the issue.

I have marked this as a bug as the analysis was not expected to work on Internal and Private classes/methods.

**Comment by AdmiringWorm** [comment]
@allcontributors please add @gep13 for bug
