### ISSUE TITLE
Raises issues for partial alias classes

### ISSUE THREAD

**Issue by pascalberger** [WormieCorp/Cake.Addin.Analyzer#9]
**Describe the bug**
I have split my addins across multiple partial classes. One of the partial classes contains the `CakeAliasCategory` attribute. The analyzer reports violation for all other partial classes.

**To Reproduce**
1. Add analyzer to https://github.com/cake-contrib/Cake.Issues

**Expected behavior**
Attributes on a partial class is valid for the whole class. 
Analyzer should takes this into account.

**Comment by AdmiringWorm** [comment]
Typically roslyn analyzers work on single files at a time, without knowing about any of the rest.
So not sure if this is possible at the moment, but it is definitely something that need to be looked into.

**Comment by AdmiringWorm** [comment]
@pascalberger you you take the [0.1.1](https://www.nuget.org/packages/Cake.Addin.Analyzer/0.1.1) release for a spin to verify that the issue is resolved?

The drawback of what I had to change, is that if no class alias category attribute is used, then only 1 of the partial classes will be marked. But I think that should be okay for now.

_(I forgot to update the GRM template to have the link to the nuget package)_

**Comment by pascalberger** [comment]
@AdmiringWorm I tried (see https://github.com/cake-contrib/Cake.Issues/pull/214). It gives the correct warnings when building (in the build output, but it misses to show the warning the error list. But might be an issue with my installation of VS.

**Comment by AdmiringWorm** [comment]
> but it misses to show the warning the error list.

I have seen that sometimes it takes quite some time for it to show up.
That is unfortunately something that is out of my control, as it is done entirely by the `Microsoft.CodeAnalysis` library.

**Comment by pascalberger** [comment]
That background processing might take some time makes sense. But in my case it doesn't appear at all in the error list. Neither in VS nor VS Code. Even after a rebuild. 

Strange thing is that rule seems to work, since it shown as warning in the build output.

**Comment by AdmiringWorm** [comment]
I got no idea why it doesn't show up in your Visual Studio instance (assuming you are using VS 2019), just added it to my Cake.Codecov library (only locally so far) and confirmed that it showed up for me.

For VS Code though, ensure that you have enabled the setting `omnisharp.enableRoslynAnalyzers` (is required for warning by analysers to show up in VS Code).
I would recommend also enabling `omnisharp.enableEditorConfigSupport` as well.

**Comment by AdmiringWorm** [comment]
@allcontributors please @pascalberger for bug

forgot to do this when the issue was closed.

**Comment by AdmiringWorm** [comment]
@allcontributors please @pascalberger for bug

**Comment by AdmiringWorm** [comment]
@allcontributors please add @pascalberger for bug

**Comment by AdmiringWorm** [comment]
Sorry about the spam, forgot the syntax to add people.

Should have added you when the issue was closed, but completely forgot about it :confounded:
